# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-31 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name=b'Kontostand')),
                ('currency', models.CharField(choices=[(b'EUR', '\u20ac'), (b'CHF', 'CHF')], max_length=3, verbose_name='W\xe4hrung')),
            ],
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'Wert')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Company')),
                ('read_acl', models.ManyToManyField(blank=True, null=True, related_name='project_readacl', to='projectroom.Person')),
                ('write_acl', models.ManyToManyField(blank=True, null=True, related_name='project_writeacl', to='projectroom.Person')),
            ],
            options={
                'ordering': ('client_company__name',),
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'Stundensatz')),
                ('initial_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'Einmaliger Satz')),
                ('currency', models.CharField(choices=[(b'EUR', '\u20ac'), (b'CHF', 'CHF')], max_length=3, verbose_name='W\xe4hrung')),
                ('rate_of_taxation', models.DecimalField(decimal_places=2, max_digits=8, verbose_name=b'Steuersatz')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Anfrage von AG'), (2, 'Gesehen von AN'), (3, 'Gestartet von AN'), (4, 'Abgebrochen von AN'), (5, 'Abgebrochen von AG'), (6, 'Warten auf Pr\xfcfung des AG'), (7, 'Gepr\xfcft von AG'), (8, 'AN wartet auf Bezahlung'), (9, 'Beendet von AN')])),
                ('duration_pre', models.IntegerField(blank=True, null=True)),
                ('duration_post', models.IntegerField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to='projectroom.Person')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Job')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_tickets', to='projectroom.Person')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.AccountEntry')),
            ],
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Person')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatusChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_status', models.IntegerField(choices=[(1, 'Anfrage von AG'), (2, 'Gesehen von AN'), (3, 'Gestartet von AN'), (4, 'Abgebrochen von AN'), (5, 'Abgebrochen von AG'), (6, 'Warten auf Pr\xfcfung des AG'), (7, 'Gepr\xfcft von AG'), (8, 'AN wartet auf Bezahlung'), (9, 'Beendet von AN')])),
                ('post_status', models.IntegerField(choices=[(1, 'Anfrage von AG'), (2, 'Gesehen von AN'), (3, 'Gestartet von AN'), (4, 'Abgebrochen von AN'), (5, 'Abgebrochen von AG'), (6, 'Warten auf Pr\xfcfung des AG'), (7, 'Gepr\xfcft von AG'), (8, 'AN wartet auf Bezahlung'), (9, 'Beendet von AN')])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.TicketItem')),
            ],
        ),
        migrations.CreateModel(
            name='TicketText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.TicketItem')),
            ],
        ),
        migrations.AddField(
            model_name='ticketaccountentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.TicketItem'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projectroom.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Project'),
        ),
        migrations.AddField(
            model_name='job',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Rate'),
        ),
        migrations.AddField(
            model_name='job',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Person'),
        ),
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Project'),
        ),
    ]
