# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-01 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='request_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='read_acl',
            field=models.ManyToManyField(blank=True, related_name='project_readacl', to='projectroom.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='write_acl',
            field=models.ManyToManyField(blank=True, related_name='project_writeacl', to='projectroom.Person'),
        ),
    ]
