# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectroom', '0004_auto_20181113_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='duration_post',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='tats\xe4chlicher Aufwand'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='duration_pre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='gesch\xe4tzter Aufwand'),
        ),
    ]
