# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectroom', '0005_auto_20181114_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filefield', models.FileField(upload_to=b'jobfile')),
                ('description', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectroom.Job')),
            ],
        ),
    ]
