# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectroom', '0006_jobfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='filefield',
            field=models.FileField(upload_to=b'jobfile', verbose_name='Datei'),
        ),
    ]
