# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-15 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectroom', '0007_auto_20181114_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='request_by',
        ),
    ]
